Repository wecode-bootcamp-korea/26-1st-Homes-frontend, pull requests merged in 2021-11, with the labels that each got.

#1 [26기 김여름] Homes-navigation bar 구현
  public/data/Categories.json
  public/data/data.js
  public/images/home.png
  public/images/premium-icon-armchair-2355336.png
  public/images/premium-icon-blanket-3328006.png
  public/images/premium-icon-magnifier-2311526.png
  public/images/premium-icon-pot-821032.png
  public/images/premium-icon-table-lamp-4408125.png
  public/images/shopping-cart (2).png
  public/images/sofa.png
  src/assets/images/list (1).png
  src/assets/images/list.png
  src/component/Nav/CategoryTable/CategoryTable.js
  src/component/Nav/CategoryTable/CategoryTable.scss
  src/component/Nav/FurnitureTable/FurnitureTable.js
  src/component/Nav/FurnitureTable/FurnitureTable.scss
  src/component/Nav/Nav.js
  src/component/Nav/Nav.scss
  src/component/Nav/component/Button.js
  src/styles/common.scss
  src/styles/variable.scss
Labels: Status: 리뷰 요청

#6 [26기 김여름] nav bar 세부 내용 수정 (button color, 카테고리 선택창 높이 등)
  public/data/Categories.json
  src/component/Nav/CategoryTable/CategoryTable.scss
  src/component/Nav/FurnitureTable/FurnitureTable.scss
  src/component/Nav/Nav.js
  src/component/Nav/Nav.scss
  src/component/Nav/component/Button.js
Labels: Status: Accepted

#7 [26기 김여름] main 이벤트 이미지 슬라이드, 베스트 10 구현
  public/data/Best.json
  public/data/Event.json
  public/images/20190715125150lBQ89aXpQD.png
  public/images/Lewisham House by Sanders & King _ Australian Interiors _ est living.png
  public/images/_ (2).jpeg
  public/images/free-icon-arrowhead-thin-outline-to-the-left-32542.png
  public/images/free-icon-right-arrow-271228.png
  public/images/star.png
  public/images/오늘도 행복한  시골집.jpeg
  src/pages/Main/Best/Best.js
  src/pages/Main/Best/Best.scss
  src/pages/Main/Event/Event.scss
  src/pages/Main/Event/Evnet.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: Status: 리뷰 요청

#8 [26기 김여름] 장바구니 페이지 레이아웃
  public/images/-.png
  public/images/HookahWoody.jpeg
  public/images/cross.png
  public/images/minus.png
  public/images/plus.png
  src/Routes.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/component/CheckBox.js
  src/pages/Cart/component/CheckBox.scss
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#9 [26기 김여름] nav bar 카테고리 클릭 시 스토어 색상변경, 링크 변경
  public/data/Categories.json
  src/component/Nav/CategoryTable/CategoryTable.js
  src/component/Nav/CategoryTable/CategoryTable.scss
  src/component/Nav/FurnitureTable/FurnitureTable.js
  src/component/Nav/FurnitureTable/FurnitureTable.scss
  src/component/Nav/Nav.js
  src/component/Nav/Nav.scss
  src/component/Nav/component/Button.js
  src/styles/variable.scss
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#11 [26기 김여름] main page beat 10 데이터 연결
  src/pages/Main/Best/Best.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#12 [26기 장세영] Login page Main 연결
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: Status: 리뷰 요청

#13 [26기 강지원 ] Add: page nation 기능 추가
  src/pages/ProductLists/ProductLists.js
Labels: Status: 리뷰 요청

#14 [26기 양성호] 별점 기능 구현 및 공용으로 함수를 사용하기위해 utils 함수 생성
  public/data/data.json
  public/images/파란별들.png
  public/images/회색별들.png
  src/Routes.js
  src/component/Utils/utils.js
  src/pages/Detail/Detail.js
  src/pages/Detail/Detail.scss
Labels: Status: 리뷰 요청

#10 [26기 김여름] nav bar 메뉴 링크 수정 및 css 수정
  src/component/Nav/CategoryTable/CategoryTable.js
  src/component/Nav/CategoryTable/CategoryTable.scss
  src/component/Nav/FurnitureTable/FurnitureTable.js
  src/component/Nav/FurnitureTable/FurnitureTable.scss
  src/component/Nav/Nav.js
  src/pages/Main/Best/Best.js
  src/pages/Main/Event/Evnet.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#5 [26기 장세영] 리뷰반영 및 사이더 수정, alert창 수정
  public/images/email.png
  public/images/lock.png
  public/images/phone.png
  public/images/user.png
  src/Routes.js
  src/component/Input/index.js
  src/component/Input/index.scss
  src/component/SignUp/Form/index.js
  src/component/SignUp/Form/index.scss
  src/component/SignUp/data.js
  src/pages/SignUp/index.js
  src/pages/SignUp/index.scss
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
  src/styles/common.scss
  src/utils/formValidator.js
Labels: Status: 수정 요청

#18 Fix: Store Link to 오류 해결 후 push
  src/Routes.js
  src/component/Modal/Modal.js
  src/component/Modal/Modal.scss
  src/pages/Detail/Detail.js
  src/pages/ProductLists/ProductLists.js
  src/pages/ProductLists/ProductLists.scss
Labels: Status: 리뷰 요청

#17 [26기 장세영] config branch생성 및 파일 생성
  src/config.js
Labels: Status: 리뷰 요청

#20 [26기 김여름] 장바구니 삭제, 수량 변경 기능 구현
  src/Routes.js
  src/component/SignUp/Form/Form.js
  src/component/SignUp/Form/Form.scss
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartContents/CartContents.js
  src/pages/Cart/CartContents/CartContents.scss
  src/pages/Cart/CartedProduct/CartedProduct.js
  src/pages/Cart/CartedProduct/CartedProduct.scss
  src/pages/Cart/CartedProductOption/CartedProductOption.js
  src/pages/Cart/CartedProductOption/CartedProductOption.scss
  src/pages/Cart/CheckBox/CheckBox.js
  src/pages/Cart/CheckBox/CheckBox.scss
  src/pages/Cart/EmptyCart/EmptyCart.js
  src/pages/Cart/EmptyCart/EmptyCart.scss
  src/pages/Cart/component/CheckBox.js
  src/pages/SignUp/Signup.js
  src/pages/SignUp/Signup.scss
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#21 [26기 김여름] fetch url 변경
  public/data/Event.json
  public/images/17560_12351_5947.jpeg
  src/component/Nav/Nav.js
  src/config.js
  src/pages/Cart/CartContents/CartContents.js
  src/pages/Main/Best/Best.scss
  src/pages/Main/Main.js
  src/pages/ProductLists/ProductLists.js
Labels: Status: 리뷰 요청

#22 [26기 강지원 ]Fix: 상세페이지 연결 문제 해결
  src/Routes.js
  src/component/ProductContainer/ProductContainer.js
  src/component/ProductContainer/ProductContainer.scss
  src/pages/Detail/Detail.js
  src/pages/Login/Login.js
  src/pages/ProductLists/ProductLists.js
  src/pages/ProductLists/ProductLists.scss
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
Labels: Status: 리뷰 요청
